### ISSUE TITLE
大佬在不

### ISSUE THREAD

**Issue by yjcaaaaaaaa** [lccurious/notion-transfer#1]
有些问题请教呀

**Comment by yjcaaaaaaaa** [comment]
就是这个同步的是哪些天的？测试下来 只有最近更新的？之前的是不是不可以

**Comment by lccurious** [comment]
是可以同步到之前的，只要使用被注释掉的这一行即可：
https://github.com/lccurious/notion-transfer/blob/32ca3107d1e9c193d50e622fd70834d47eb0e968/douban/sync.py#L44C67-L44C67
2006年差不多是最初始的日期，你也可以调到自己的账号注册那天

**Comment by yjcaaaaaaaa** [comment]
感谢回复！ 可以再详细一点不 抱歉 我弄失败了。。。。具体该怎么使用？需要注释掉原有的哪些来使用这一行？



> 是可以同步到之前的，只要使用被注释掉的这一行即可： https://github.com/lccurious/notion-transfer/blob/32ca3107d1e9c193d50e622fd70834d47eb0e968/douban/sync.py#L44C67-L44C67 2006年差不多是最初始的日期，你也可以调到自己的账号注册那天

**Comment by yjcaaaaaaaa** [comment]
我通过修改timedelta(days=1)成功了！但是测试下来有个小问题 为什么有些条目会导入失败？https://movie.douban.com/subject/36245461/
https://movie.douban.com/subject/36080790/
这两个网页导入几次都失败
一个是
![image](https://github.com/lccurious/notion-transfer/assets/143862871/76bfd08e-4606-4dde-ab1a-3a8fc70429b1)
一个是
![image](https://github.com/lccurious/notion-transfer/assets/143862871/7d63fa0b-aec6-462f-8b74-9e2954261fb8)

**Comment by lccurious** [comment]
> 感谢回复！ 可以再详细一点不 抱歉 我弄失败了。。。。具体该怎么使用？需要注释掉原有的哪些来使用这一行？
> 
> > 是可以同步到之前的，只要使用被注释掉的这一行即可： https://github.com/lccurious/notion-transfer/blob/32ca3107d1e9c193d50e622fd70834d47eb0e968/douban/sync.py#L44C67-L44C67 2006年差不多是最初始的日期，你也可以调到自己的账号注册那天

这个函数 `def _load_last_sync_time(self)` 的意思返回一个上次同步时间。其他的函数会根据这个日期来确认是否停止再查找更早的更新内容。

**Comment by lccurious** [comment]
> 我通过修改timedelta(days=1)成功了！但是测试下来有个小问题 为什么有些条目会导入失败？https://movie.douban.com/subject/36245461/ https://movie.douban.com/subject/36080790/ 这两个网页导入几次都失败 一个是 ![image](https://user-images.githubusercontent.com/143862871/265757626-76bfd08e-4606-4dde-ab1a-3a8fc70429b1.png) 一个是 ![image](https://user-images.githubusercontent.com/143862871/265757744-7d63fa0b-aec6-462f-8b74-9e2954261fb8.png)

这是因为这几个日期格式不标准，之后可以考虑加入异常检查来自动提取其中的日期字段。

**Comment by lccurious** [comment]
> > 我通过修改timedelta(days=1)成功了！但是测试下来有个小问题 为什么有些条目会导入失败？https://movie.douban.com/subject/36245461/ https://movie.douban.com/subject/36080790/ 这两个网页导入几次都失败 一个是 ![image](https://user-images.githubusercontent.com/143862871/265757626-76bfd08e-4606-4dde-ab1a-3a8fc70429b1.png) 一个是 ![image](https://user-images.githubusercontent.com/143862871/265757744-7d63fa0b-aec6-462f-8b74-9e2954261fb8.png)
> 
> 这是因为这几个日期格式不标准，之后可以考虑加入异常检查来自动提取其中的日期字段。

日期字段不标准的问题已经通过正则表达式兼容
