### ISSUE TITLE
大佬，我发现有好多图片加载不出来

### ISSUE THREAD

**Issue by yjcaaaaaaaa** [lccurious/notion-transfer#2]
看了一眼，您使用的地址尾缀是m的，我测试了另一个人的那个人的图片都比较全，看了一眼是s尾缀，是不是大小问题？有些条目没有m大小的地址

**Comment by yjcaaaaaaaa** [comment]
`sync.py ERROR 处理 {'comment': '', 'rating': None, 'sharing_text': 'https://movie.douban.com/subject/1297186/ 来自@豆瓣App', 'sharing_url': 'https://www.douban.com/doubanapp/dispatch?uri=/subject/1297186/interest/3965250737', 'tags': [], 'charts': [], 'platforms': [], 'vote_count': 0, 'create_time': '2023-10-17 15:31:58', 'status': 'mark', 'id': 3965250737, 'is_private': False, 'subject': {'rating': {'count': 271, 'max': 10, 'star_count': 4.0, 'value': 7.7}, 'controversy_reason': '', 'pubdate': ['1971-12-14'], 'pic': {'large': 'https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2101929986.jpg', 'normal': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2101929986.jpg'}, 'honor_infos': [{'kind': 'movie', 'uri': 'douban://douban.com/subject_collection/ECEUILPQA?type=rank&category=movie&rank_type=award_movie', 'rank': 3, 'title': '第22届柏林国际电影节获奖名单'}], 'is_show': False, 'vendor_icons': [], 'year': '1971', 'card_subtitle': '1971 / 美国 / 剧情 喜剧 / 阿瑟·希勒 / 乔治·C·斯科特 黛安娜·里格', 'id': '1297186', 'genres': ['剧情', '喜剧'], 'title': '医生故事', 'is_released': True, 'actors': [{'name': '乔治·C·斯科特'}, {'name': '黛安娜·里格'}, {'name': '巴纳德·休斯'}], 'color_scheme': {'is_dark': True, 'primary_color_light': 'a5a5a4', '_base_color': [0.25, 0.008368200836820053, 0.9372549019607843], 'secondary_color': 'f7f9f4', '_avg_color': [0.16666666666666666, 0.009090909090909188, 0.8627450980392157], 'primary_color_dark': '7e7f7e'}, 'type': 'movie', 'has_linewatch': False, 'vendor_desc': '', 'cover_url': 'https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2101929986.jpg', 'sharing_url': 'https://movie.douban.com/subject/1297186/', 'url': 'https://movie.douban.com/subject/1297186/', 'release_date': None, 'uri': 'douban://douban.com/movie/1297186', 'subtype': 'movie', 'directors': [{'name': '阿瑟·希 勒'}], 'album_no_interact': False, 'article_intros': [], 'null_rating_reason': ''}} 遇到错误: 'NoneType' object is not subscriptable
Thu 26 Oct 2023 18:52:59 _client.py INFO HTTP Request: POST https://api.notion.com/v1/databases/c2236c58-41a2-401b-92f0-4a8988afc89c/query "HTTP/1.1 200 OK"
Thu 26 Oct 2023 18:53:00 sync.py ERROR 处理 {'comment': '', 'rating': None, 'sharing_text': 'https://movie.douban.com/subject/1297421/ 来自@豆瓣App', 'sharing_url': 'https://www.douban.com/doubanapp/dispatch?uri=/subject/1297421/interest/3965248298', 'tags': [], 'charts': [], 'platforms': [], 'vote_count': 0, 'create_time': '2023-10-17 15:28:57', 'status': 'mark', 'id': 3965248298, 'is_private': False, 'subject': {'rating': {'count': 2242, 'max': 10, 'star_count': 3.5, 'value': 7.3}, 'controversy_reason': '', 'pubdate': ['1983-12-09'], 'pic': {'large': 'https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2511885991.jpg', 'normal': 'https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2511885991.jpg'}, 'honor_infos': [], 'is_show': False, 'vendor_icons': [], 'year': '1983', 'card_subtitle': '1983 / 美国 / 恐怖 / 约翰·卡朋特 / 基斯·戈登 约翰·斯托克韦尔', 'id': '1297421', 'genres': ['恐怖'], 'title': '克莉丝汀魅力', 'is_released': True, 'actors': [{'name': '基斯·戈登'}, {'name': '约翰·斯托克韦尔'}, {'name': '亚历姗卓拉·保罗'}, {'name': '罗伯特·普罗斯基'}, {'name': '哈利·戴恩·斯坦通'}, {'name': '克里斯汀·贝尔福德'}, {'name': '罗伯茨·布洛瑟姆'}, {'name': 'William Ostrander'}, {'name': 'David Spielberg'}, {'name': 'Malcolm Danare'}, {'name': 'Steven Tash'}, {'name': 'Stuart Charno'}, {'name': '凯利·普雷斯顿'}, {'name': 'Marc Poppel'}, {'name': 'Robert Darnell'}], 'color_scheme': {'is_dark': True, 'primary_color_light': '3e4272', '_base_color': [0.6515151515151515, 0.4583333333333333, 0.09411764705882353], 'secondary_color': 'f4f5f9', '_avg_color': [0.6333333333333333, 0.2884615384615384, 0.20392156862745098], 'primary_color_dark': '292c4c'}, 'type': 'movie', 'has_linewatch': False, 'vendor_desc': '', 'cover_url': 'https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2511885991.jpg', 'sharing_url': 'https://movie.douban.com/subject/1297421/', 'url': 'https://movie.douban.com/subject/1297421/', 'release_date': None, 'uri': 'douban://douban.com/movie/1297421', 'subtype': 'movie', 'directors': [{'name': '约翰·卡朋特'}], 'album_no_interact': False, 'article_intros': [], 'null_rating_reason': ''}} 遇到错误: 'NoneType' object is not subscriptable`

Thu 26 Oct 2023 18:50:09 _client.py INFO HTTP Request: POST https://api.notion.com/v1/databases/c2236c58-41a2-401b-92f0-4a8988afc89c/query "HTTP/1.1 200 OK"
Thu 26 Oct 2023 18:50:11 sync.py ERROR 处理 {'comment': '', 'rating': {'count': 1, 'max': 5, 'star_count': 5.0, 'value': 5}, 'sharing_text': '我的评分：★★★★★ https://movie.douban.com/subject/1781126/ 来自@豆瓣App', 'sharing_url': 'https://www.douban.com/doubanapp/dispatch?uri=/subject/1781126/interest/3969573195', 'tags': [], 'charts': [], 'platforms': [], 'vote_count': 0, 'create_time': '2023-10-22 03:54:59', 'status': 'done', 'id': 3969573195, 'is_private': False, 'subject': {'rating': {'count': 200027, 'max': 10, 'star_count': 4.0, 'value': 7.5}, 'controversy_reason': '', 'pubdate': ['2007-03-02(美国)'], 'pic': {'large': 'https://img1.doubanio.com/view/photo/m_ratio_poster/public/p470486287.jpg', 'normal': 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p470486287.jpg'}, 'honor_infos': [], 'is_show': False, 'vendor_icons': ['https://img2.doubanio.com/f/frodo/8286b9b5240f35c7e59e1b1768cd2ccf0467cde5/pics/vendors/migu_video.png', 'https://img9.doubanio.com/f/frodo/fbc90f355fc45d5d2056e0d88c697f9414b56b44/pics/vendors/tencent.png', 'https://img9.doubanio.com/f/frodo/88a62f5e0cf9981c910e60f4421c3e66aac2c9bc/pics/vendors/bilibili.png'], 'year': '2007', 'card_subtitle': '2007 / 美国 / 剧情 悬疑 惊悚 传记 犯罪 / 大卫·芬奇 / 杰克·吉伦哈尔 马克·鲁弗洛', 'id': '1781126', 'genres': ['剧情', '悬疑', '惊悚'], 'title': '十二宫', 'is_released': True, 'actors': [{'name': '杰克·吉伦哈尔'}, {'name': '马克·鲁弗洛'}, {'name': '安东尼·爱德华兹'}, {'name': '小罗伯特·唐尼'}, {'name': '布莱恩·考克斯'}, {'name': '约翰·卡洛·林奇'}, {'name': '里奇蒙德·阿奎特'}, {'name': '鲍勃·斯蒂芬森'}, {'name': '约翰·莱西'}, {'name': '科洛 ·塞维尼'}, {'name': '艾德·塞特拉基安'}, {'name': '约翰·盖兹'}, {'name': '约翰·特里'}, {'name': '坎迪·克拉克'}, {'name': '伊莱亚斯·科泰斯'}], 'color_scheme': {'is_dark': True, 'primary_color_light': '517272', '_base_color': [0.5, 0.29230769230769227, 0.2549019607843137], 'secondary_color': 'f4f9f9', '_avg_color': [0.5069444444444443, 0.2727272727272727, 0.34509803921568627], 'primary_color_dark': '364c4c'}, 'type': 'movie', 'has_linewatch': True, 'vendor_desc': '', 'cover_url': 'https://img1.doubanio.com/view/photo/m_ratio_poster/public/p470486287.jpg', 'sharing_url': 'https://movie.douban.com/subject/1781126/', 'url': 'https://movie.douban.com/subject/1781126/', 'release_date': None, 'uri': 'douban://douban.com/movie/1781126', 'subtype': 'movie', 'directors': [{'name': '大卫·芬奇'}], 'album_no_interact': False, 'article_intros': [], 'null_rating_reason': ''}} 遇到错误: 'NoneType' object is not subscriptable

**Comment by yjcaaaaaaaa** [comment]
又出现了一些失败，这几个失败好像前一个版本是没问题的，好像不是时间问题？

**Comment by yjcaaaaaaaa** [comment]
我是直接跑在了原来的数据库中，会有冲突吗，还是要初始化新数据库重新跑一遍

**Comment by yjcaaaaaaaa** [comment]
Thu 26 Oct 2023 19:31:02 notion_database.py ERROR 创建电影 雾之外 失败:body failed validation. Fix one:
body.properties.主演.multi_select[0].id should be defined, instead was `undefined`.
body.properties.主演.multi_select[0].name should be populated, instead was `""`.
Thu 26 Oct 2023 19:31:02 notion_database.py INFO 创建电影 雾之外

还有这个

**Comment by lccurious** [comment]
遇到错误: 'NoneType' object is not subscriptable 是因为片长的正则表达式错误导致当前内容的细节无法正确更新，已经修正

**Comment by lccurious** [comment]
> Thu 26 Oct 2023 19:31:02 notion_database.py ERROR 创建电影 雾之外 失败:body failed validation. Fix one: body.properties.主演.multi_select[0].id should be defined, instead was `undefined`. body.properties.主演.multi_select[0].name should be populated, instead was `""`. Thu 26 Oct 2023 19:31:02 notion_database.py INFO 创建电影 雾之外
> 
> 还有这个

这个条目似乎已经被豆瓣删去

**Comment by lccurious** [comment]
> 看了一眼，您使用的地址尾缀是m的，我测试了另一个人的那个人的图片都比较全，看了一眼是s尾缀，是不是大小问题？有些条目没有m大小的地址



> 看了一眼，您使用的地址尾缀是m的，我测试了另一个人的那个人的图片都比较全，看了一眼是s尾缀，是不是大小问题？有些条目没有m大小的地址

所有的封面都是按照数据抓取时刻详情页对应的图片地址。之后封面无法加载可能是由于当前的服务器修改了封面图片存储位置，Notion中的存储记录还是旧的。如果变动的项特别多可以考虑增加图片可访问检查。
